CREATE TABLE STUDENTS
(
stud_id INT(11) NOT NULL AUTO_INCREMENT,
NAME VARCHAR(50) NOT NULL,
email VARCHAR(50) NOT NULL,
dob DATE DEFAULT NULL,
PRIMARY KEY (stud_id)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;